### Archivo para hacer nuestras consultas al servidor






###Crear una nueva tarea:
//(content-type: application/json)para que mande la información al body como JSON
POST http://localhost:3000/api/v1/tareas
content-type: application/json

{
    "tarea": "Esta es una nueva tarea prolija",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### ELIMINAR TAREA

DELETE http://localhost:3000/api/v1/tareas/25


### Obtener la tarea 36

GET http://localhost:3000/api/v1/tareas/36

### Actualizar tarea

PUT http://localhost:3000/api/v1/tareas/25
content-type: application/json

{
    "tarea": "EXPRESS INSTALADO",
    "completado": true,
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}