### Archivo para hacer nuestras consultas al servidor






###Crear una nueva tarea:
//(content-type: application/json)para que mande la información al body como JSON
POST http://localhost:3000/api/v1/tareas
content-type: application/json

{
    "tarea": "Esta es una nueva tarea",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### ELIMINAR TAREA

DELETE http://localhost:3000/api/v1/tareas/25

